feat: #LOOL-91 add config
OPEN-ENT-NG/lool-connector pull request #10
Opened 2023-07-13 16:36 UTC by FlorentMr

## Describe your changes
Adds /config for lool.

## Checklist tests
Try the url /lool/config

## Issue ticket number and link
[LOOL-91](https://jira.support-ent.fr/browse/LOOL-91)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-07-17 07:04 UTC, JinDouang approved these changes

2023-07-17 09:26 UTC, qperie requested changes

2023-07-17 09:26 UTC, qperie commented on src/main/java/fr/openent/lool/controller/LoolController.java
> +    @ResourceFilter(AdminFilter.class)
```suggestion
    @ResourceFilter(SuperAdminFilter.class)
```

2023-07-18 08:14 UTC, flmartineau approved these changes

2023-07-26 09:09 UTC, merged